### PR TITLE
Backend development branch

### PR DESCRIPTION
**Pull request by j97051**
- move scripts in script.js

### CODE REVIEW

**Review by orsoknows — APPROVED** [review]
Backend code is working to my knowledge, conflicts in script.js shouldn't break code

**Review by SulikowJ — DISMISSED** [review]
addImage call removed from this merge - this is incorrect, will be reverted once I have finished implementing save

**Comment by j97051** [comment]
from @aaknox: hey guys this merge failed the quality gate check. please refactor the code to reduce the new bugs/code smells.

**Review by orsoknows — APPROVED** [review]
Looks good to me

EDIT: didn't see the new sonarcloud check failure

**Review by orsoknows — APPROVED** [review]
I fixed the sonarcloud bugs that were found, the code smells are related to TODO areas of the code that will not be present in later iterations, but should be present for reference until later testing is completed.

**Pull request merged**
